/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// noinspection JSUnusedGlobalSymbols
// Generated by unplugin-auto-import
// biome-ignore lint: disable
export {}
declare global {
  const useAuth: typeof import('./composables/useAuth.js')['default']
  const useAvatar: typeof import('./composables/useAvatar.js')['default']
  const useDeviceInfo: typeof import('./composables/useDeviceInfo.js')['default']
  const useDialog: typeof import('./composables/useDialog.js')['default']
  const useFormatter: typeof import('./composables/useFormatter.js')['default']
  const useGameMode: typeof import('./composables/useGameMode.js')['default']
  const useGameScene: typeof import('./composables/useGameScene.js')['default']
  const useTime: typeof import('./composables/useTime.js')['default']
  const useWordblock: typeof import('./composables/useWordblock.js')['default']
}
