/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// noinspection JSUnusedGlobalSymbols
// Generated by unplugin-auto-import
// biome-ignore lint: disable
export {}
declare global {
  const useAuth: typeof import('./composables/useAuth.js')['default']
  const useAvatar: typeof import('./composables/useAvatar.js')['default']
  const useCensorBadwords: typeof import('./composables/useCensorBadwords.js')['default']
  const useChoices: typeof import('./composables/useChoices.js')['default']
  const useCreatorForm: typeof import('./composables/useCreatorForm.js')['default']
  const useDeviceInfo: typeof import('./composables/useDeviceInfo.js')['default']
  const useDialog: typeof import('./composables/useDialog.js')['default']
  const useDrawSocket: typeof import('./composables/useDrawSocket.js')['useDrawSocket']
  const useFile: typeof import('./composables/useFile.js')['default']
  const useFlashcards: typeof import('./composables/useFlashcards.js')['default']
  const useFormatter: typeof import('./composables/useFormatter.js')['default']
  const useGameMode: typeof import('./composables/useGameMode.js')['default']
  const useGameScene: typeof import('./composables/useGameScene.js')['default']
  const useScroll: typeof import('./composables/useScroll.js')['default']
  const useSfx: typeof import('./composables/useSfx.js')['useSfx']
  const useTime: typeof import('./composables/useTime.js')['default']
  const useWordblock: typeof import('./composables/useWordblock.js')['default']
}
