export const APP_NAME = 'parolla'
export const APP_DOMAIN = 'parolla.app'
export const APP_URL = 'https://parolla.app'
export const PUBLISHER_NAME = 'Selim Doyranlı'
export const PUBLISHER_DOMAIN = 'selimdoyranli.com'
export const PUBLISHER_URL = 'https://selimdoyranli.com'
export const ANSWER_CHAR_LENGTH = 64
export const GAME_TIME_LIMIT = 60 * 5 * 1000 // 5min
export const UNSUPPORTED_HEIGHT = 520
export const USERNAME_REGEX = /^(?!.*\.\.)(?!.*\.$)[^\W][\w.]{0,29}$/
export const ROOM_TAG_REGEX = /[^\p{L}\p{N}]/gu
export const WORDBLOCK_AVAILABLE_LENGTHS = [5, 6, 7]
export const WORDBLOCK_MAX_ATTEMPTS = 6
