export default () => ({
  status: 'idle',
  channel: 'draw',
  publicRooms: [],
  room: null,
  players: [],
  hostId: null,
  myId: null,
  roundIndex: 0,
  roundCount: 0,
  drawerId: null,
  drawerName: null,
  currentWord: null,
  maskedWord: null,
  category: null,
  durationMs: 0,
  remainingMs: 0,
  strokes: [],
  chat: [],
  wordOptions: null,
  pickTimeoutMs: 0,
  iAmDrawer: false,
  iAmHost: false,
  iGuessedCorrectly: false,
  lastRoundResult: null,
  finalScores: null,
  lastError: null
})
